Opal 966
309thEDDGE/opal-helm pull request #46
Opened 2024-10-01 12:28 UTC by MM-USAF

Keycloak script is updated to reflect changes to simplify start up.  You will need to log into key cloak first and create a new user.  Add them to the jupyterhub_staff group and log into jupyterhub

2024-10-07 17:18 UTC, EF-USAF requested changes

2024-10-07 17:18 UTC, EF-USAF commented on apps/keycloak/keycloak-setup.sh
> +echo "creating minio test user"
This block is for creating opaluser, do we need this for the k8s deployment?

2024-10-07 17:18 UTC, EF-USAF commented on apps/keycloak/keycloak-setup.sh
> +./kcadm.sh update users/$MINIO_ADMIN_ID/groups/$JUPYTERHUB_STAFF_GROUP_ID -r master -s realm=master -s userId=$MINIO_ADMIN_ID -s groupId=$JUPYTERHUB_STAFF_GROUP_ID -n
I'm not sure we want the keycloak admin to be able to do anything other than user setup in keycloak

2024-10-16 15:51 UTC, EF-USAF approved these changes, later dismissed
looks good

2024-10-16 15:55 UTC, EF-USAF approved these changes

2024-10-16 15:56 UTC, JP-USAF approved these changes

2024-10-16 15:56 UTC, merged